local https = require("ssl.https")
local http = require("socket.http")
local ltn12 = require("ltn12")
local logger = require("logger")
local CacheManager = require("image_cache_manager")

local PollinationsClient = {}

-- Pollinations.ai - Completely FREE, no API key, no registration
-- Simple REST endpoint that returns images directly
local BASE_URL = "https://image.pollinations.ai/prompt/"

function PollinationsClient.generateImage(prompt)
    if not prompt or prompt == "" then
        return nil, "Prompt cannot be empty."
    end

    logger.info("Pollinations: Generating image for prompt:", prompt)

    -- URL encode the prompt
    local encoded_prompt = prompt:gsub("([^%w%-%_%.%~])", function(c)
        return string.format("%%%02X", string.byte(c))
    end)
    
    local url = BASE_URL .. encoded_prompt
    
    -- Additional parameters (optional, but help improve quality)
    url = url .. "?width=1024&height=1024&seed=" .. math.random(1, 999999)
    
    local response_chunks = {}
    local ok, status_code, headers, status_line = http.request {
        url = url,
        method = "GET",
        redirect = true, -- Follow redirects
        sink = ltn12.sink.table(response_chunks),
    }

    if not ok or status_code ~= 200 then
        logger.warn("Pollinations: API request failed", status_code, status_line)
        return nil, "API Error: " .. (status_line or status_code or "Unknown")
    end

    local image_data = table.concat(response_chunks)
    
    if not image_data or #image_data < 100 then
        logger.warn("Pollinations: No valid image data received")
        return nil, "Invalid image data received"
    end

    -- Save to Cache
    local filename = "ai_pollinations_" .. os.time() .. "_" .. math.random(1000, 9999) .. ".jpg"
    local cache_dir = CacheManager.getCacheDir()
    local full_path = cache_dir .. "/" .. filename

    local f = io.open(full_path, "wb")
    if not f then
        return nil, "Failed to save image to cache"
    end
    f:write(image_data)
    f:close()

    logger.info("Pollinations: Image saved to", full_path)
    
    return {
        {
            title = prompt,
            description = "Generated by Pollinations.ai (Free & Open Source)",
            thumbnail_url = "file://" .. full_path,
            full_url = "file://" .. full_path,
            is_local = true,
            local_path = full_path
        }
    }
end

return PollinationsClient
